codecov:
  branch: main
  require_ci_to_pass: no

coverage:
  status:
    patch:
      default:
        target: '100'
    project:
      default:
        target: '95'
      api:
        flags:
          - python
      dashboard:
        flags:
          - javascript

  flags:
    python:
      paths:
        - api
      carryforward: true
    javascript:
      paths:
        - dashboard
      carryforward: true

comment: false
github_checks:
  annotations: false
