name: build

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*.*.*'

jobs:
  publish-image:
    runs-on: ubuntu-latest
    # if: github.repository == 'solarperformanceinsight/solarperformanceinsight'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: quay.io/solarperformanceinsight/solarperformanceinsight
          tag-sha: true

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Quay.io
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}

  update-deployment:
    runs-on: ubuntu-latest
    # if: github.repository == 'solarperformanceinsight/solarperformanceinsight'
    needs:
      - publish-image
    steps:
      - uses: actions/checkout@v2
        with:
          repository: alorenzo175/spi-deploy
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: 3.8.1

      - name: Set ref
        id: sharef
        run: |
          echo "::set-output name=ref::$(echo ${GITHUB_SHA} | cut -b -12)"

      - name: Make PR
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git checkout -b deploy/${REF}
          echo 'kustomize' > newfile
          git add .
          git commit -m 'Update '${IMG}' to '${REF}
          git push origin deploy/${REF}
          gh pr create --fill
        env:
          REF: ${{ steps.sharef.outputs.ref }}
          IMG: image
