name: Test Database

on:
  push:
  pull_request:
    paths:
      - 'db/**'
    branches:
      - main

jobs:
  test-database:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - uses: mirromutth/mysql-action@v1.1
        with:
          mysql version: '8.0.21'
          mysql database: 'spi_data'
          mysql root password: 'testpassword'

      - name: Install Dependencies
        run: |
          cd db
          python -m pip install --upgrade pip
          pip install -r test-requirements.txt
          pip list

      - name: Migrate database
        env:
          DATABASE_URL: "mysql://root:testpassword@127.0.0.1:3306/spi_data"
        run: |
          curl -fsSL -o ./dbmate https://github.com/amacneil/dbmate/releases/latest/download/dbmate-linux-amd64
          chmod +x ./dbmate
          ./dbmate --wait up

      - name: Test
        run: pytest db
