name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-test.txt
          pip install .

      - name: Test
        run: |
          pytest solarperformanceinsight_api --cov --cov-report=xml

      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: adder,subtractor,pypi
          fail_ci_if_error: true
        if: ${{ always() }}
